// Code generated by MockGen. DO NOT EDIT.
// Source: ../config.go
//
// Generated by this command:
//
//	mockgen -source=../config.go -destination=./config.go
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigInitRepository is a mock of ConfigInitRepository interface.
type MockConfigInitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigInitRepositoryMockRecorder
	isgomock struct{}
}

// MockConfigInitRepositoryMockRecorder is the mock recorder for MockConfigInitRepository.
type MockConfigInitRepositoryMockRecorder struct {
	mock *MockConfigInitRepository
}

// NewMockConfigInitRepository creates a new mock instance.
func NewMockConfigInitRepository(ctrl *gomock.Controller) *MockConfigInitRepository {
	mock := &MockConfigInitRepository{ctrl: ctrl}
	mock.recorder = &MockConfigInitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigInitRepository) EXPECT() *MockConfigInitRepositoryMockRecorder {
	return m.recorder
}

// SaveWithTemplate mocks base method.
func (m *MockConfigInitRepository) SaveWithTemplate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithTemplate")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWithTemplate indicates an expected call of SaveWithTemplate.
func (mr *MockConfigInitRepositoryMockRecorder) SaveWithTemplate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithTemplate", reflect.TypeOf((*MockConfigInitRepository)(nil).SaveWithTemplate))
}
