// Code generated by MockGen. DO NOT EDIT.
// Source: ../profile.go
//
// Generated by this command:
//
//	mockgen -source=../profile.go -destination=./profile.go -package=mock_domain
//

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	entity "github.com/canpok1/ai-feed/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// LoadProfile mocks base method.
func (m *MockProfileRepository) LoadProfile() (*entity.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProfile")
	ret0, _ := ret[0].(*entity.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProfile indicates an expected call of LoadProfile.
func (mr *MockProfileRepositoryMockRecorder) LoadProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProfile", reflect.TypeOf((*MockProfileRepository)(nil).LoadProfile))
}

// MockProfileTemplateRepository is a mock of ProfileTemplateRepository interface.
type MockProfileTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileTemplateRepositoryMockRecorder is the mock recorder for MockProfileTemplateRepository.
type MockProfileTemplateRepositoryMockRecorder struct {
	mock *MockProfileTemplateRepository
}

// NewMockProfileTemplateRepository creates a new mock instance.
func NewMockProfileTemplateRepository(ctrl *gomock.Controller) *MockProfileTemplateRepository {
	mock := &MockProfileTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockProfileTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileTemplateRepository) EXPECT() *MockProfileTemplateRepositoryMockRecorder {
	return m.recorder
}

// SaveProfileTemplate mocks base method.
func (m *MockProfileTemplateRepository) SaveProfileTemplate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProfileTemplate")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProfileTemplate indicates an expected call of SaveProfileTemplate.
func (mr *MockProfileTemplateRepositoryMockRecorder) SaveProfileTemplate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProfileTemplate", reflect.TypeOf((*MockProfileTemplateRepository)(nil).SaveProfileTemplate))
}
