# golangci-lint設定ファイル
# コード品質測定ツールの設定

run:
  # タイムアウト設定（デフォルトは1分）
  timeout: 5m

  # 並列実行数（0はCPUコア数と同じ）
  concurrency: 0

  # テスト対象のディレクトリ
  tests: true

  # ビルドタグ
  build-tags:
    - integration

# 出力設定
output:
  # 出力フォーマット: colored-line-number|line-number|json|tab|checkstyle|code-climate
  formats:
    - format: colored-line-number

  # 結果の表示順序
  sort-results: true

# リンター設定
linters:
  # すべてのリンターを無効化してから必要なものだけ有効化
  disable-all: true

  enable:
    # エラーチェック漏れの検出
    - errcheck

    # セキュリティ脆弱性の検出
    - gosec

    # 循環的複雑度のチェック
    - gocyclo

    # コード重複の検出
    - dupl

    # 無効な代入の検出
    - ineffassign

    # 不要な型変換の検出
    - unconvert

    # コードスタイルのチェック
    - gocritic

    # 基本的な静的解析
    - govet
    - staticcheck

    # 未使用の変数・定数・関数の検出
    # - unused  # 既存コードの修正が必要なため一旦除外

    # コードの簡素化提案
    - gosimple

    # 型アサーションのチェック
    - typecheck

    # フォーマットのチェック
    - gofmt
    # - goimports  # 既存コードで広範囲に使用されているため一旦除外

    # ミススペルのチェック
    - misspell

    # コメントのチェック
    # - godot  # 既存コードの修正が必要なため一旦除外

    # nilチェックの検出
    # - nilnil  # 既存コードの修正が必要なため一旦除外

    # エラーハンドリングのチェック
    - errname
    - errorlint

    # パフォーマンス改善の提案
    # - prealloc  # 既存コードの修正が必要なため一旦除外

    # 構造体タグのバリデーション
    - gomoddirectives
    - gomodguard

# 各リンターの詳細設定
linters-settings:
  # 循環的複雑度の閾値設定
  gocyclo:
    # 関数の複雑度の上限（推奨: 10-15、段階的導入のため30に設定）
    min-complexity: 30

  # コード重複の設定
  dupl:
    # 重複とみなすトークン数の閾値
    threshold: 100

  # セキュリティチェックの設定
  gosec:
    # 除外するルール
    # TODO: 段階的にセキュリティチェックを有効化する
    # - G301, G302: ファイル/ディレクトリパーミッション（次期対応予定）
    # - G304: ファイル読み込み（次期対応予定）
    excludes:
      - G301  # ディレクトリパーミッション（0755 -> 0750への変更を検討）
      - G302  # ファイルパーミッション（0666/0644 -> 0600への変更を検討）
      - G304  # ファイル読み込み（filepath.Clean()の使用を検討）
      - G404  # 弱い乱数生成（推薦機能で使用、セキュリティクリティカルではない）
      - G104  # エラーハンドリング（errcheckと重複）
    # 信頼度レベル: low, medium, high
    confidence: medium

  # エラーチェックの設定
  errcheck:
    # エラーチェックを除外する関数
    exclude-functions:
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (io.Closer).Close
      - (*os.File).Close
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Println
      - (io.Writer).Write
      - os.Remove

  # コードスタイルチェックの設定
  gocritic:
    # 有効化するチェック
    enabled-tags:
      - diagnostic
      - style
      - performance

    # 無効化するチェック（段階的導入のため）
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - hugeParam  # 既存コードの大規模修正が必要なため一旦除外
      - octalLiteral  # Go 1.13以前の形式で広範囲に使用されているため一旦除外
      - emptyStringTest  # コードスタイルの問題のため一旦除外
      - unlambda  # コードスタイルの問題のため一旦除外
      - unnamedResult  # コードスタイルの問題のため一旦除外
      - appendCombine  # コードスタイルの問題のため一旦除外
      - paramTypeCombine  # コードスタイルの問題のため一旦除外
      - elseif  # コードスタイルの問題のため一旦除外

  # インポート順序のチェック
  goimports:
    # ローカルパッケージのプレフィックス
    local-prefixes: github.com/canpok1/ai-feed

  # nilチェックの設定
  nilnil:
    # nilとnilの比較を検出
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

  # エラーハンドリングの設定
  errorlint:
    # %wを使ったエラーラップのチェック
    errorf: true
    # エラー比較のチェック
    comparison: true
    # 型アサーションのチェック（段階的導入のため一旦無効化）
    asserts: false

# 除外設定
issues:
  # 除外するパターン
  exclude-rules:
    # テストファイルでの一部チェックを無効化
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck

    # 生成されたファイルを除外
    - path: mock_.*\.go
      linters:
        - all

    # main関数でのエラーチェック除外
    - path: main\.go
      linters:
        - errcheck
      text: "Error return value is not checked"

  # デフォルトの除外ルールを使用しない
  exclude-use-default: false

  # 同じ問題の最大表示回数（0は無制限）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 新しい問題のみ報告（falseですべての問題を報告）
  new: false
