// Code generated by MockGen. DO NOT EDIT.
// Source: ../config.go
//
// Generated by this command:
//
//	mockgen -source=../config.go -destination=mock_config.go -package=mock_infra ConfigRepository
//

// Package mock_infra is a generated GoMock package.
package mock_infra

import (
	reflect "reflect"

	infra "github.com/canpok1/ai-feed/internal/infra"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigRepository is a mock of ConfigRepository interface.
type MockConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockConfigRepositoryMockRecorder is the mock recorder for MockConfigRepository.
type MockConfigRepositoryMockRecorder struct {
	mock *MockConfigRepository
}

// NewMockConfigRepository creates a new mock instance.
func NewMockConfigRepository(ctrl *gomock.Controller) *MockConfigRepository {
	mock := &MockConfigRepository{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepository) EXPECT() *MockConfigRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockConfigRepository) Load() (*infra.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*infra.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigRepositoryMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigRepository)(nil).Load))
}

// Save mocks base method.
func (m *MockConfigRepository) Save(config *infra.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigRepositoryMockRecorder) Save(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigRepository)(nil).Save), config)
}

// Mockmerger is a mock of merger interface.
type Mockmerger[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockmergerMockRecorder[T]
	isgomock struct{}
}

// MockmergerMockRecorder is the mock recorder for Mockmerger.
type MockmergerMockRecorder[T any] struct {
	mock *Mockmerger[T]
}

// NewMockmerger creates a new mock instance.
func NewMockmerger[T any](ctrl *gomock.Controller) *Mockmerger[T] {
	mock := &Mockmerger[T]{ctrl: ctrl}
	mock.recorder = &MockmergerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmerger[T]) EXPECT() *MockmergerMockRecorder[T] {
	return m.recorder
}

// Merge mocks base method.
func (m *Mockmerger[T]) Merge(arg0 T) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Merge", arg0)
}

// Merge indicates an expected call of Merge.
func (mr *MockmergerMockRecorder[T]) Merge(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*Mockmerger[T])(nil).Merge), arg0)
}
