description = "PRのレビューコメントを元にタスクファイルを作成"
prompt = """
PR {{args}} にレビューコメントが投稿されました。
対応要否を判断し、対応が必要なものを1ファイル1タスクとして tmp/todo フォルダにファイルを作成してください。

## タスクファイルのフォーマット

### ファイル名

pr_{PRの番号}_task_{2桁0埋めの1からの連番}_{タスク概要(英語)}.md

例）PR #1 に対するタスクの場合、 `pr_1_task_01_sample_task.md` となる

### ファイル内容のテンプレート

```
## 対応内容の概要

## 対応内容の詳細

### 編集対象ファイル

### 完了条件 

### 備考
```

"""
