# AI Feedの設定ファイル
# このファイルには全プロファイル共通のデフォルト設定を定義します
default_profile:
  # AI設定
  ai:
    gemini:
      type: gemini-2.5-flash                  # 使用するGeminiモデル
      api_key: xxxxxx                         # Google AI Studio APIキー

  # プロンプト設定
  system_prompt: あなたはXXXXなAIアシスタントです。    # AIに与えるシステムプロンプト
  
  # 記事紹介文生成用のプロンプトテンプレート
  # 利用可能なパラメータ:
  #   {{.Title}}   - 記事のタイトル
  #   {{.Link}}    - 記事のURL
  #   {{.Content}} - 記事の本文内容
  comment_prompt_template: |
    以下の記事の紹介文を100字以内で作成してください。
    ---
    記事タイトル: {{.Title}}
    記事URL: {{.Link}}
    記事内容:
    {{.Content}}
  
  fixed_message: 固定の文言です。                     # 記事紹介文に追加する固定文言

  # 出力先設定
  output:
    # Slack投稿設定
    slack_api:
      api_token: xxxxxx                       # Slack Bot Token
      channel: "#general"                     # 投稿先チャンネル
      
      # Slackメッセージテンプレート（オプション）
      # 利用可能なパラメータ:
      #   {{.Comment}}         - AIが生成したコメント（存在する場合のみ）
      #   {{.Article.Title}}   - 記事のタイトル
      #   {{.Article.Link}}    - 記事のURL
      #   {{.Article.Content}} - 記事の本文内容
      #   {{.FixedMessage}}    - 固定メッセージ（設定されている場合のみ）
      # 条件分岐:
      #   {{if .Comment}}...{{end}}      - コメントが存在する場合のみ表示
      #   {{if .FixedMessage}}...{{end}} - 固定メッセージが存在する場合のみ表示
      message_template: |
        {{if .Comment}}{{.Comment}}
        {{end}}{{.Article.Title}}
        {{.Article.Link}}{{if .FixedMessage}}
        {{.FixedMessage}}{{end}}
    
    # Misskey投稿設定
    misskey:
      api_token: xxxxxx                       # Misskeyアクセストークン
      api_url: https://misskey.social/api     # MisskeyのAPIエンドポイント