# AI Feedの設定ファイル
# このファイルには全プロファイル共通のデフォルト設定を定義します
default_profile:
  # AI設定
  ai:
    gemini:
      # 使用するGeminiモデル
      # 下記URLの仕様に従ったモデルバージョン名を指定してください。
      # https://ai.google.dev/gemini-api/docs/models?hl=ja#model-versions
      type: gemini-2.5-flash

      # Gemini APIキー
      # キーを直接指定する場合は api_key 環境変数から読み込む場合は api_key_env
      # api_keyとapi_key_envの両方が指定された場合、api_keyが優先されます
      # api_key: xxxxxx
      api_key_env: GEMINI_API_KEY

  # システムプロンプト
  # AIの性格などを指定
  system_prompt: |
    あなたは次の特徴を持っています。
    - 陽気な性格
  
  # 記事紹介文生成用のプロンプトテンプレート
  # 利用可能なパラメータ:
  #   {{TITLE}}   - 記事のタイトル
  #   {{URL}}     - 記事のURL
  #   {{CONTENT}} - 記事の本文内容
  comment_prompt_template: |
    以下の記事の紹介文を100字以内で作成してください。
    ---
    記事タイトル: {{TITLE}}
    記事URL: {{URL}}
    記事内容:
    {{CONTENT}}
  
  # 記事紹介文に追加する固定文言
  fixed_message: ※固定の文言です。

  # 出力先設定
  output:
    # Slack投稿設定
    # 投稿しない場合は削除するか、enabled: false を設定してください。
    slack_api:
      # 有効/無効フラグ（省略時はtrue）
      # false に設定すると一時的に無効化できます
      enabled: false
      
      # Slack のトークン
      # 直接指定する場合は api_token 環境変数から読み込む場合は api_token_env
      # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
      # api_token: xxxxxx
      api_token_env: SLACK_TOKEN
      
      # 投稿先チャンネル(#付き)
      channel: "#general"
      
      # メッセージテンプレート
      # 利用可能なパラメータ:
      #   {{COMMENT}}       - AIが生成したコメント
      #   {{TITLE}}         - 記事のタイトル
      #   {{URL}}           - 記事のURL
      #   {{CONTENT}}       - 記事の本文内容
      #   {{FIXED_MESSAGE}} - 固定メッセージ
      message_template: |
        {{COMMENT}}
        <{{URL}}|{{TITLE}}>
        {{FIXED_MESSAGE}}
    
    # Misskey投稿設定
    # 投稿しない場合は削除するか、enabled: false を設定してください。
    misskey:
      # 有効/無効フラグ（省略時はtrue）
      # false に設定すると一時的に無効化できます
      enabled: false
      
      # Misskey のアクセストークン
      # 直接指定する場合は api_token 環境変数から読み込む場合は api_token_env
      # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
      # api_token: xxxxxx
      api_token_env: MISSKEY_TOKEN

      # Misskey のサーバーのURL
      api_url: https://example.com
      
      # メッセージテンプレート
      # 利用可能なパラメータ:
      #   {{COMMENT}}       - AIが生成したコメント
      #   {{TITLE}}         - 記事のタイトル
      #   {{URL}}           - 記事のURL
      #   {{CONTENT}}       - 記事の本文内容
      #   {{FIXED_MESSAGE}} - 固定メッセージ
      message_template: |
        {{COMMENT}}
        [{{TITLE}}]({{URL}})
        {{FIXED_MESSAGE}}

# キャッシュ設定
cache:
  # 有効/無効フラグ（省略時はfalse）
  # trueに設定すると投稿済み記事の重複を防ぐことができます
  enabled: false
  
  # キャッシュファイルのパス
  # 省略時はホームディレクトリの ~/.ai-feed/recommend_history.jsonl が使用されます
  # file_path: ~/.ai-feed/recommend_history.jsonl
  
  # 最大エントリ数（FIFOで古いものから削除）
  # 省略時は1000件
  # max_entries: 1000
  
  # 保持期間（日数）
  # 指定日数を過ぎた記事は自動的に削除されます
  # 省略時は30日
  # retention_days: 30
