# AI Feedのプロファイル設定ファイル
# このファイルの設定は config.yml のデフォルトプロファイル設定を上書きします
#
# ===============================================================================
# 設定値の必須/任意について
# ===============================================================================
# [必須]: 設定が必須な項目です。省略するとバリデーションエラーになります。
# [任意]: 省略可能な項目です。省略した場合はデフォルト値が使用されるか、機能が無効になります。
# [条件付き必須]: 特定の条件下で必須となる項目です。
#
# ===============================================================================
# profile checkコマンドの検証ルール
# ===============================================================================
# profile check [file] コマンドは以下の順序で検証を行います:
#
# 1. config.ymlのデフォルトプロファイル(default_profile)を読み込む
# 2. プロファイルファイルが指定されている場合:
#    - プロファイルファイルの設定がデフォルトプロファイルを上書き（マージ）
# 3. マージされた最終的なプロファイルに対してバリデーションを実行
#
# つまり、プロファイルファイル単体で全ての必須項目を満たす必要はなく、
# config.ymlのデフォルトプロファイルと合わせて必須項目が揃っていればOKです。
#
# 例: config.ymlでAI設定を定義し、プロファイルでoutput設定だけを変更する場合
#     プロファイルにはoutput設定のみ記載すれば、config.ymlのAI設定が使われます。
# ===============================================================================

# =============================================================================
# AI設定 [必須]
# =============================================================================
# config.ymlで設定済みの場合は省略可能（config.ymlの設定が使われます）
ai:
  gemini:
    # 使用するGeminiモデル [必須]
    # Google Gemini APIで利用可能な任意のモデル名を指定できます。
    # 利用可能なモデルの一覧は下記URLを参照してください。
    # https://ai.google.dev/gemini-api/docs/models?hl=ja#model-versions
    #
    # 例: gemini-2.5-flash, gemini-1.5-pro, gemini-1.5-flash, gemini-2.0-flash-exp など
    type: gemini-2.5-flash

    # Gemini APIキー [必須: api_keyまたはapi_key_envのどちらか一方]
    # キーを直接指定する場合は api_key、環境変数から読み込む場合は api_key_env
    # api_keyとapi_key_envの両方が指定された場合、api_keyが優先されます
    # api_key: xxxxxx
    api_key_env: GEMINI_API_KEY

# =============================================================================
# プロンプト設定
# =============================================================================

# システムプロンプト [必須]
# AIの性格などを指定
# config.ymlで設定済みの場合は省略可能
system_prompt: |
  あなたは次の特徴を持っています。
  - 陽気な性格

# 記事紹介文生成用のプロンプトテンプレート [必須]
# config.ymlで設定済みの場合は省略可能
# 利用可能なパラメータ:
#   {{TITLE}}   - 記事のタイトル
#   {{URL}}     - 記事のURL
#   {{CONTENT}} - 記事の本文内容
comment_prompt_template: |
  以下の記事の紹介文を100字以内で作成してください。
  ---
  記事タイトル: {{TITLE}}
  記事URL: {{URL}}
  記事内容:
  {{CONTENT}}

# 記事選択用のプロンプト [必須]
# config.ymlで設定済みの場合は省略可能
# 複数の記事から1つを選択する際にAIに与える指示
selector_prompt: |
  以下の記事一覧から、最も興味深い記事を1つ選択してください。

# 記事紹介文に追加する固定文言 [任意]
# メッセージテンプレートで {{FIXED_MESSAGE}} として使用できます
fixed_message: ※固定の文言です。

# =============================================================================
# 出力先設定 [必須: 少なくとも1つの出力先が有効である必要があります]
# =============================================================================
# config.ymlで設定済みの場合は省略可能
output:
  # ---------------------------------------------------------------------------
  # Slack投稿設定 [任意]
  # ---------------------------------------------------------------------------
  # 投稿しない場合は削除するか、enabled: false を設定してください。
  slack_api:
    # 有効/無効フラグ [任意: デフォルト=true]
    # false に設定すると一時的に無効化できます
    # 無効化すると、以下の設定は検証されません
    enabled: false

    # Slack のトークン [条件付き必須: enabled=trueの場合必須]
    # botスコープの chat:write に加えて、表示名やアイコンを変更する場合は chat:write.customize が必要です
    # 直接指定する場合は api_token、環境変数から読み込む場合は api_token_env
    # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
    # api_token: xxxxxx
    api_token_env: SLACK_TOKEN

    # 投稿先チャンネル [条件付き必須: enabled=trueの場合必須]
    # チャンネル名は#付きで指定
    channel: "#general"

    # メッセージテンプレート [条件付き必須: enabled=trueの場合必須]
    # 利用可能なパラメータ:
    #   {{.Comment}}       - AIが生成したコメント
    #   {{.Article.Title}} - 記事のタイトル
    #   {{.Article.Link}}  - 記事のURL
    #   {{.FixedMessage}}  - 固定メッセージ
    message_template: |
      {{if .Comment}}{{.Comment}}\n{{end}}<{{.Article.Link}}|{{.Article.Title}}>{{if .FixedMessage}}\n{{.FixedMessage}}{{end}}

    # 表示名 [任意]
    # username: "AI Feed Bot"

    # アイコンURL [任意: icon_emojiとの併用不可]
    # icon_url: "https://example.com/bot_icon.png"

    # アイコン絵文字 [任意: icon_urlとの併用不可]
    # icon_emoji: ":robot_face:"

  # ---------------------------------------------------------------------------
  # Misskey投稿設定 [任意]
  # ---------------------------------------------------------------------------
  # 投稿しない場合は削除するか、enabled: false を設定してください。
  misskey:
    # 有効/無効フラグ [任意: デフォルト=true]
    # false に設定すると一時的に無効化できます
    # 無効化すると、以下の設定は検証されません
    enabled: false

    # Misskey のアクセストークン [条件付き必須: enabled=trueの場合必須]
    # 直接指定する場合は api_token、環境変数から読み込む場合は api_token_env
    # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
    # api_token: xxxxxx
    api_token_env: MISSKEY_TOKEN

    # Misskey のサーバーのURL [条件付き必須: enabled=trueの場合必須]
    # 有効なURL形式で指定してください
    api_url: https://example.com

    # メッセージテンプレート [条件付き必須: enabled=trueの場合必須]
    # 利用可能なパラメータ:
    #   {{COMMENT}}       - AIが生成したコメント
    #   {{TITLE}}         - 記事のタイトル
    #   {{URL}}           - 記事のURL
    #   {{CONTENT}}       - 記事の本文内容
    #   {{FIXED_MESSAGE}} - 固定メッセージ
    message_template: |
      {{COMMENT}}
      [{{TITLE}}]({{URL}})
      {{FIXED_MESSAGE}}
