# AI Feedのプロファイル設定ファイル
# このファイルの設定は config.yml のデフォルトプロファイル設定を上書きします
#
# 設定値の必須/任意、検証ルールの詳細はREADME.mdの「設定リファレンス」を参照してください。
# https://github.com/canpok1/ai-feed#設定リファレンス

# AI設定
ai:
  # AIモック設定
  # モックを有効にすると、実際のGemini APIを呼び出さずにテスト用の固定レスポンスを返します。
  # 初回セットアップ時や開発・テスト時に便利です。
  # 本番運用時は enabled: false に変更し、Gemini設定を有効化してください。
  mock:
    # 有効/無効フラグ
    # true: モックを使用（Gemini APIキー不要）
    # false: 実際のGemini APIを使用
    enabled: true

    # 記事選択モード
    # first: 最初の記事を選択
    # random: ランダムに選択
    # last: 最後の記事を選択
    selector_mode: first

    # モックが返す固定コメント
    comment: "これはテスト用のモックコメントです。"

  gemini:
    # 使用するGeminiモデル
    # Google Gemini APIで利用可能な任意のモデル名を指定できます。
    # 利用可能なモデルの一覧は下記URLを参照してください。
    # https://ai.google.dev/gemini-api/docs/models?hl=ja#model-versions
    #
    # 例: gemini-2.5-flash, gemini-1.5-pro, gemini-1.5-flash, gemini-2.0-flash-exp など
    type: gemini-2.5-flash

    # Gemini APIキー
    # キーを直接指定する場合は api_key 環境変数から読み込む場合は api_key_env
    # api_keyとapi_key_envの両方が指定された場合、api_keyが優先されます
    # api_key: xxxxxx
    api_key_env: GEMINI_API_KEY

# システムプロンプト
# AIの性格などを指定
system_prompt: |
  あなたは次の特徴を持っています。
  - 陽気な性格

# 記事紹介文生成用のプロンプトテンプレート
# 利用可能なパラメータ:
#   {{TITLE}}   - 記事のタイトル
#   {{URL}}     - 記事のURL
#   {{CONTENT}} - 記事の本文内容
comment_prompt_template: |
  以下の記事の紹介文を100字以内で作成してください。
  ---
  記事タイトル: {{TITLE}}
  記事URL: {{URL}}
  記事内容:
  {{CONTENT}}

# 記事選択用のプロンプト
# 複数の記事から1つを選択する際にAIに与える指示
selector_prompt: |
  以下の記事一覧から、最も興味深い記事を1つ選択してください。

# 記事紹介文に追加する固定文言
fixed_message: ※固定の文言です。

# 出力先設定
output:
  # Slack投稿設定
  # 投稿しない場合は削除するか、enabled: false を設定してください。
  slack_api:
    # 有効/無効フラグ（省略時はtrue）
    # false に設定すると一時的に無効化できます
    enabled: false

    # Slack のトークン
    # botスコープの chat:write に加えて、表示名やアイコンを変更する場合は chat:write.customize が必要です
    # 直接指定する場合は api_token 環境変数から読み込む場合は api_token_env
    # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
    # api_token: xxxxxx
    api_token_env: SLACK_TOKEN

    # 投稿先チャンネル(#付き)
    channel: "#general"

    # メッセージテンプレート
    # 利用可能なパラメータ:
    #   {{.Comment}}       - AIが生成したコメント
    #   {{.Article.Title}} - 記事のタイトル
    #   {{.Article.Link}}  - 記事のURL
    #   {{.FixedMessage}}  - 固定メッセージ
    message_template: |
      {{if .Comment}}{{.Comment}}\n{{end}}<{{.Article.Link}}|{{.Article.Title}}>{{if .FixedMessage}}\n{{.FixedMessage}}{{end}}

    # 表示名（省略可）
    # username: "AI Feed Bot"

    # アイコンURL（省略可・icon_emojiとの併用不可）
    # icon_url: "https://example.com/bot_icon.png"

    # アイコン絵文字（省略可・icon_urlとの併用不可）
    # icon_emoji: ":robot_face:"

  # Misskey投稿設定
  # 投稿しない場合は削除するか、enabled: false を設定してください。
  misskey:
    # 有効/無効フラグ（省略時はtrue）
    # false に設定すると一時的に無効化できます
    enabled: false

    # Misskey のアクセストークン
    # 直接指定する場合は api_token 環境変数から読み込む場合は api_token_env
    # api_tokenとapi_token_envの両方が指定された場合、api_tokenが優先されます
    # api_token: xxxxxx
    api_token_env: MISSKEY_TOKEN

    # Misskey のサーバーのURL
    api_url: https://example.com

    # メッセージテンプレート
    # 利用可能なパラメータ:
    #   {{COMMENT}}       - AIが生成したコメント
    #   {{TITLE}}         - 記事のタイトル
    #   {{URL}}           - 記事のURL
    #   {{CONTENT}}       - 記事の本文内容
    #   {{FIXED_MESSAGE}} - 固定メッセージ
    message_template: |
      {{COMMENT}}
      [{{TITLE}}]({{URL}})
      {{FIXED_MESSAGE}}
